apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: morse-code
spec:
  broker: default
  filter:
    attributes:
      source: morse-code
  subscriber:
    ref:
     apiVersion: flows.knative.dev/v1
     kind: Sequence
     name: morse-code-sequence
