apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: morse-code-service
spec:
  template:
    metadata:
    spec:
      containers:
        - image: ghcr.io/holoed/morse-code:master
          
