apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: morse-code-sequence
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  steps:
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: morse-code
      uri: /encode
  reply:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: cloudevents-player